// <auto-generated />
using FTM.WebApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FTM.WebApi.Migrations
{
    [DbContext(typeof(FtmDbContext))]
    [Migration("20191030194326_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("FTM.WebApi.Entities.CredentialInfo", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<string>("ExpiresIn");

                    b.Property<string>("IdToken");

                    b.Property<string>("Issued");

                    b.Property<string>("IssuedUtc");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Scope");

                    b.Property<string>("TokenType");

                    b.HasKey("UserId");

                    b.ToTable("CredentialInfos");
                });

            modelBuilder.Entity("FTM.WebApi.Entities.RoomInfo", b =>
                {
                    b.Property<string>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoomName");

                    b.HasKey("RoomId");

                    b.ToTable("RoomInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
